### ISSUE TITLE
Congratulations and help

### ISSUE THREAD

**Issue by virla01** [Artem-Schander/L5ModularDocs#1]
Hello I am testing L5 Modular and I really like it, but I would like to know if there is any way to be able to separate the modules by backend and frontend

**Comment by Artem-Schander** [comment]
Hi @virla01,

If I understand correctly, you want to add ne more layer to your folder structure. If so, that is currently not possible. 
However, it should be pretty simple to implement. I would appreciate a PR. Otherwise wait till the next minor release.

BTW. This is the wrong repo. This one is only for the docs. Please checkout the right one in the future: https://github.com/Artem-Schander/L5Modular
